spring:
  datasource:
    url: jdbc:mysql://localhost/db_siscom
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    datasource-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
logging:
  level:
    org:
      hibernate:
        SQL: debug